added problem 2182-1431-1768-151-1207
Sreedevi-27/Problem-Solving pull request #7
Opened 2023-09-11 18:01 UTC by Sreedevi-27

2023-09-15 03:31 UTC, sharathr25 requested changes

2023-09-15 03:31 UTC, sharathr25 commented on src/main/java/algorithms/leetcode/medium/GroupOfPeople.java
> +
this problem can be refactored

2023-09-15 03:31 UTC, sharathr25 commented on src/main/java/algorithms/leetcode/medium/ReverseWordsInAString.java
> +        System.out.println(Arrays.toString(sArray));
remove this

2023-09-15 03:31 UTC, sharathr25 commented on src/main/java/algorithms/leetcode/medium/ReverseWordsInAString.java
> +                result += sArray[i]+" ";
use StringBuilder whenever you need to concatenate strings

2023-09-15 03:31 UTC, sharathr25 commented on src/main/java/algorithms/leetcode/medium/ReverseWordsInAString.java
> +        int sArrayLength = sArray.length;
If the usage is only once then no need to store array length in variable use it directly

2023-09-15 03:31 UTC, sharathr25 commented on src/test/java/algorithms/leetcode/medium/GroupOfPeopleTest.java
> +        expectedGroupPeople.add(list3);
you can do something like
```
List<List<Integer>> expectedGroupPeople = Arrays.asList(Arrays.asList(5), Arrays.asList(0,1,2), Arrays.asList(3,4,6))
```

2023-09-15 13:49 UTC, sharathr25 commented on src/test/java/algorithms/leetcode/medium/ReverseWordsInAStringTest.java
> +    void testReverseString(){
Without @Test annotation how this test ran? Did you run the test?

2023-09-18 01:35 UTC, sharathr25 requested changes

2023-09-18 01:35 UTC, sharathr25 commented on src/main/java/algorithms/leetcode/easy/KidsWithGreaterCandies.java
> +            boolean b = (isKidsHaveGreatestCandies.add(candy + extraCandies >= maxCandy));
Whats this b. and where r u using this

2023-09-18 01:35 UTC, sharathr25 commented on src/main/java/algorithms/leetcode/easy/MergeStringAlternatively.java
> +        int word2Length = word2.length();
word1.length() used only once. So u can directly use it. No need to create a variable. Same for word2.length(). 

Keep in mind if its used only once don't create a variable for it.

2023-09-18 01:35 UTC, sharathr25 commented on src/main/java/algorithms/leetcode/easy/MergeStringAlternatively.java
> +            mergedString.append(j < word2Length ? word2.charAt(j++) : "");
Only for true we need to append so use if condition.

2023-09-18 01:35 UTC, sharathr25 commented on src/main/java/algorithms/leetcode/easy/MergeStringAlternatively.java
> +        for(int i=0,j=0;  i<word1Length||j<word2Length; ){
👌

2023-09-18 01:35 UTC, sharathr25 commented on src/main/java/algorithms/leetcode/easy/UniqueOccurence.java
> +        return (uniqueElement.size() == numberOccurences.size());
👌

2023-09-18 01:35 UTC, sharathr25 commented on src/main/java/algorithms/leetcode/medium/ReverseWordsInAString.java
> +                result.append(sArray[i]).append(" ");
Here sArray[i] getting used twice. So u can store this in a variable.

2023-09-18 20:22 UTC, Sreedevi-27 commented on src/main/java/algorithms/leetcode/medium/GroupOfPeople.java
> +
Done ✅

2023-09-18 22:09 UTC, sharathr25 approved these changes

2023-09-18 22:09 UTC, merged